### ISSUE TITLE
Link in repo description is wrong

### ISSUE THREAD

**Issue by mvpasarel** [widgetic/widgeticjs#1]
When I go to https://docs.widgetic.com/ link in repo description I get insecure connection alert.

The non-https version of the docs http://docs.widgetic.com/ seems to work fine tho.

**Comment by cristinecula** [comment]
Hello @mvpasarel
Thank you for the notice! It's fixed now thanks to you :)

Have you tried out the API? Any feedback you can provide us with is very much appreciated!
